---
- name: "Add frequently used applications to the dock"
  hosts: localhost
  vars:
    dockitems_to_remove:
      - Mail
      - Contacts
      - Maps
      - Calendar
    dockitems_to_persist:
      - name: Obsidian
        path: "/Applications/Obsidian.app/"
      - name: Visual Studio Code
        path: "/Applications/Visual\ Studio\ Code.app/"

  tasks:
    - name: Remove applications docked by default
      shell: dockutil --remove "{{ item }}"
      ignore_errors: true
      with_items: "{{ dockitems_to_remove }}"

    - name: Add applications to dock
      shell: dockutil --add "{{ item.path }}"
      with_items: "{{dockitems_to_persist}}"
