---
- name: "Configure ruby development environment"
  hosts: localhost

  tasks:
    - name: Get latest stable ruby version
      shell: rbenv install -l | grep -v - | tail -1 | tr -d '[[:space:]]'
      register: ruby_version

    - name: Set ruby version
      set_fact: ruby_version={{ ruby_version.stdout }}

    - name: Install latest stable ruby
      shell: rbenv install {{ ruby_version }}

    - name: Set default ruby
      shell: rbenv global {{ ruby_version }}