---
- name: "Configure OS X settings"
  hosts: localhost

  tasks:
    - name: Make screenshots folder
      file: 
        path: ~/Pictures/Screenshots
        state: directory

    - name: Set screenshots folder
      shell: defaults write com.apple.screencapture location -string "~/Pictures/Screenshots"

    - name: Show status bar in finder
      shell: |
        defaults write com.apple.finder ShowStatusBar -bool true
        defaults write com.apple.finder ShowPathbar -bool true

    - name: Configure TextEdit
      shell: |
        defaults write com.apple.TextEdit NSDocumentSaveNewDocumentsToCloud -bool false
        defaults write com.apple.TextEdit NSShowSavePanelWhenOpeningNewDocument -bool false
        defaults write com.apple.TextEdit RichText -int 0
        defaults write com.apple.TextEdit SmartQuotes -bool false
        defaults write com.apple.TextEdit SmartDashes -bool false
