---
- name: "Configure OS X settings"
  hosts: localhost

  tasks:
    - name: Make screenshots folder
      file: 
        path: ~/Screenshots
        state: directory

    - name: Set screenshots folder
      shell: defaults write com.apple.screencapture location -string "~/Screenshots"

    - name: Show status bar in finder
      shell: defaults write com.apple.finder ShowStatusBar -bool true

    - name: Show path in finder
      shell: defaults write com.apple.finder ShowPathbar -bool true

    - name: Use plain text mode for textedit
      shell: defaults write com.apple.TextEdit RichText -int 0